# Generated by Django 4.1.4 on 2022-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_description_photo_image_photo_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
